version: "3.9"

volumes:
  db_pg:
  data:

services:
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./db_pg:/var/lib/postgresql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  dataloading:
    build: .
    command: python load_data_dbs.py
    volumes:
      - ./data:/code/data
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    depends_on:
      - postgres_db
